export const faqs = [
  { q: 'Does Replaid include an AI agent?', a: 'You bring your own agent. It provides the reasoning, business knowledge, and reply instructions. Replaid connects the channels, supplies conversation context, applies action policies, and records the results.' },
  { q: 'Which channels can I connect?', a: 'Instagram Business or Creator accounts for text DMs and comments, Facebook Pages for Messenger, and Telegram bots for private text messages. Each team can connect one active account per channel. Past conversations are not imported. WhatsApp is planned and is not currently available.' },
  { q: 'Can I try it without sending replies?', a: 'Yes. Keep sending disabled and allow draft replies. Your agent can read a conversation and save a draft in Replaid without sending it to the customer.' },
  { q: 'Does connecting MCP turn on automatic replies?', a: 'No. An MCP connection makes tools available when your client runs. Automatic processing needs an external agent schedule or a webhook receiver that starts your agent. Replaid does not create that trigger.' },
  { q: 'Can a person take over?', a: 'Yes. Your agent can escalate a conversation and pause its automation. A person can handle it in the native channel, then resume automation when appropriate. The handoff is recorded in the action log.' },
  { q: 'Do I need to write code?', a: 'A compatible MCP client can connect through its settings and Replaid authorization. Custom REST integrations and webhook receivers require technical setup. Client support and account requirements vary.' },
  { q: 'What does Replaid cost?', a: 'There is no subscription. Current supported operations are free. Future paid operations use prepaid USD credits with provider cost plus a 20% markup; applicable tax is separate. Your AI provider or agent platform may charge separately.' },
];
